import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home({ externalPostData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>My blog </h1>
        <div className={styles.grid}>
          <div className={styles.card}>
            <Link href="/post/first-post">
              <h3>First Post </h3>
            </Link>
            <p>Ini adalah artikel yang dari first post</p>
          </div>
          <div className={styles.card}>
            <Link href="/post/second-post">
              <h3>Second Post</h3>
            </Link>
            <p>Ini adalah data yang ada di dalam second first</p>
          </div>
          {externalPostData.map((data) => {
            return (
              <div className={styles.card} key={data.id}>
                <Link href={data.link}>
                  <h3>{data.title}</h3>
                </Link>
                <p>{data.excerpt}</p>
              </div>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by &copy; Lombok Code Space
      </footer>
    </div>
  );
}

// getStaticProps
export async function getStaticProps() {
  const apiURL = "http://localhost:3001/post";
  const response = await fetch(apiURL);
  const data = await response.json();

  return {
    props: {
      externalPostData: data,
    },
  };
}
